// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAzNdjjHMoN-fsxphKWoVsF6F0WdF3Js',
    appId: '1:902287675450:web:e0246b9798e07d8ecca503',
    messagingSenderId: '902287675450',
    projectId: 'clone-8bad6',
    authDomain: 'clone-8bad6.firebaseapp.com',
    storageBucket: 'clone-8bad6.appspot.com',
    measurementId: 'G-2H23BFX3R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBImRuGRBkLZvi2XcOZw4nZ5WmwPaxTYsA',
    appId: '1:902287675450:android:07b54464d1f2ff41cca503',
    messagingSenderId: '902287675450',
    projectId: 'clone-8bad6',
    storageBucket: 'clone-8bad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo-P_xTMPnP4Y2lvX_4n7FHAenBe0Mhvs',
    appId: '1:902287675450:ios:179afc79d9e03506cca503',
    messagingSenderId: '902287675450',
    projectId: 'clone-8bad6',
    storageBucket: 'clone-8bad6.appspot.com',
    iosBundleId: 'com.example.ibroximjon.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo-P_xTMPnP4Y2lvX_4n7FHAenBe0Mhvs',
    appId: '1:902287675450:ios:1a9a73c97e7cc504cca503',
    messagingSenderId: '902287675450',
    projectId: 'clone-8bad6',
    storageBucket: 'clone-8bad6.appspot.com',
    iosBundleId: 'com.example.ibroximjon.amazonClone.RunnerTests',
  );
}
